# Generated by Django 4.2.1 on 2023-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0002_remove_movimentacao_datahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
