# Generated by Django 4.2.1 on 2023-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0004_cliente_data_e_hora_cliente_tentativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_e_hora',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
    ]
