# Generated by Django 4.2.1 on 2023-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0005_alter_cliente_data_e_hora_alter_cliente_tentativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='nome_titular',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='nome_titular_cartao',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='numero_conta',
        ),
    ]
