# Generated by Django 4.2.1 on 2023-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0006_remove_cartao_nome_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='nome_titular',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
