# Generated by Django 4.2.1 on 2023-06-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbank', '0007_cartao_nome_titular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='fk_conta_cartao',
            new_name='fk_conta',
        ),
    ]
